name: Build and test code
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.5'

      - name: Build code
        run: go build ./...
      - name: Run tests
        run: go test ./...

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
         CC_TEST_REPORTER_ID: 39890c211762e1d6d9bb1e5bf04d20f707559a340b8ffaf7695cf27d547e2b34
        with:
          coverageCommand: bash -c "go test -coverprofile=c.out ./... && sed -i 's|roob.re/tcache/||' c.out"